"use client";

import { useState, useRef, useEffect } from "react";
import { Download, Copy, FileText, Printer, Check, ChevronDown } from "lucide-react";

interface ExportMenuProps {
  content: string;
  title?: string;
}

export default function ExportMenu({ content, title = "PriceRadar AI Report" }: ExportMenuProps) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    if (open) document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  const copyMarkdown = async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => {
      setCopied(false);
      setOpen(false);
    }, 1500);
  };

  const downloadTxt = () => {
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/\s+/g, "-").toLowerCase()}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setOpen(false);
  };

  const printPdf = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <style>
    @media print { @page { margin: 1in; } }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; font-size: 14px; line-height: 1.7; color: #18181b; max-width: 800px; margin: 0 auto; padding: 2rem; }
    h1 { font-size: 1.5rem; margin-bottom: 0.25rem; color: #0891b2; }
    .meta { font-size: 0.8rem; color: #71717a; margin-bottom: 2rem; border-bottom: 1px solid #e4e4e7; padding-bottom: 1rem; }
    pre { white-space: pre-wrap; word-wrap: break-word; font-family: inherit; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div class="meta">Generated by PriceRadar AI &middot; ${new Date().toLocaleDateString()}</div>
  <pre>${content.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre>
</body>
</html>`);
    printWindow.document.close();
    printWindow.onload = () => printWindow.print();
    setOpen(false);
  };

  if (!content) return null;

  return (
    <div ref={menuRef} className="relative inline-flex">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1.5 text-xs text-cyan-400 hover:text-cyan-300 transition-colors px-2 py-1.5 rounded-lg hover:bg-cyan-500/10"
      >
        <Download className="w-3.5 h-3.5" />
        Export
        <ChevronDown className={`w-3 h-3 transition-transform ${open ? "rotate-180" : ""}`} />
      </button>

      {open && (
        <div className="absolute right-0 top-full mt-1.5 w-52 rounded-xl border border-white/10 py-1.5 z-50 shadow-2xl" style={{ background: "var(--bg-secondary, #111)" }}>
          <button
            onClick={copyMarkdown}
            className="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-gray-400 hover:text-white hover:bg-white/5 transition-colors"
          >
            {copied ? <Check className="w-4 h-4 text-cyan-400" /> : <Copy className="w-4 h-4" />}
            {copied ? "Copied!" : "Copy Markdown"}
          </button>
          <button
            onClick={downloadTxt}
            className="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-gray-400 hover:text-white hover:bg-white/5 transition-colors"
          >
            <FileText className="w-4 h-4" />
            Download .txt
          </button>
          <div className="mx-3 my-1 border-t border-white/10" />
          <button
            onClick={printPdf}
            className="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-gray-400 hover:text-white hover:bg-white/5 transition-colors"
          >
            <Printer className="w-4 h-4" />
            Print / PDF
          </button>
        </div>
      )}
    </div>
  );
}
